# #day= loop+range

# for i in range(1,6):
#     print(i)



# # range and loop kii help see 2 ki table
# for i in range(0, 22, 2):
#     print(i)

# #countdown ulti table 2 ki
# for i in range(20, 0, -2):
#      print(i)


# #line m kitne word hai 
# lenth=["pan","copy","paper"]
# for i in range(len(lenth)):
#     print(i ,lenth[i])




# #creat year list 
# years=[]
# for y in range(2009,2026):
#     years.append(y)
#     print(years)




